# Generated by Django 3.1.3 on 2020-11-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arogyam', '0002_arogyamfliper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArogyamService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('slug', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='static/arogyam/service')),
            ],
        ),
        migrations.AlterField(
            model_name='arogyamfliper',
            name='image',
            field=models.ImageField(default='', upload_to='static/arogyam/fliper'),
        ),
    ]
