# Generated by Django 3.1.3 on 2020-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arogyam', '0003_auto_20201125_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArogyamBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=50)),
                ('slug', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='static/arogyam/brand')),
            ],
        ),
    ]
