# Generated by Django 3.1.3 on 2020-11-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneycare', '0003_filesadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesadmin',
            name='author',
        ),
        migrations.AddField(
            model_name='filesadmin',
            name='content',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='filesadmin',
            name='image',
            field=models.ImageField(default='', upload_to='static/kidneycare/pdf'),
        ),
    ]
