# Generated by Django 3.1.3 on 2020-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneycare', '0004_auto_20201122_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
    ]
