# Generated by Django 3.1.3 on 2020-11-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneycare', '0007_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(default='', upload_to='static/kidneycare/disease'),
        ),
    ]
