# Generated by Django 3.1.3 on 2020-11-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneycare', '0008_auto_20201124_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='disease',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
    ]
