# Generated by Django 3.1.3 on 2020-11-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidneycare', '0009_auto_20201124_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='price',
        ),
    ]
