# Generated by Django 3.1.3 on 2020-11-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneycare', '0010_remove_disease_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=50)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
