# Generated by Django 3.1.3 on 2020-11-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneycare', '0012_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='static/kidneycare/event'),
        ),
    ]
